### ISSUE TITLE
Problem converting a model to Torch Script via tracing

### ISSUE THREAD

**Issue by marcodeltutto** [facebookresearch/SparseConvNet#156]
Hello! 
I am not sure if this is supported, but I am failing to convert a SparseConvNet model to Torch Script via tracing. I am following the instructions [here](https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing).
Below is a minimal reproducible example of the error I get. This is the same example in the SparseConvNet README.md file, with the additions of this line at the end:
```python
traced_script_module = torch.jit.trace(model, input)
```
Any help is appreciated! Thanks!

Code:
```python
import torch
import sparseconvnet as scn

# Use the GPU if there is one, otherwise CPU
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

model = scn.Sequential().add(
    scn.SparseVggNet(2, 1,
                     [['C', 8], ['C', 8], ['MP', 3, 2],
                      ['C', 16], ['C', 16], ['MP', 3, 2],
                      ['C', 24], ['C', 24], ['MP', 3, 2]])
).add(
    scn.SubmanifoldConvolution(2, 24, 32, 3, False)
).add(
    scn.BatchNormReLU(32)
).add(
    scn.SparseToDense(2, 32)
).to(device)

# output will be 10x10
inputSpatialSize = model.input_spatial_size(torch.LongTensor([10, 10]))
input_layer = scn.InputLayer(2, inputSpatialSize)

msgs = [[" X   X  XXX  X    X    XX     X       X   XX   XXX   X    XXX   ",
         " X   X  X    X    X   X  X    X       X  X  X  X  X  X    X  X  ",
         " XXXXX  XX   X    X   X  X    X   X   X  X  X  XXX   X    X   X ",
         " X   X  X    X    X   X  X     X X X X   X  X  X  X  X    X  X  ",
         " X   X  XXX  XXX  XXX  XX       X   X     XX   X  X  XXX  XXX   "],

        [" XXX              XXXXX      x   x     x  xxxxx  xxx ",
         " X  X  X   XXX       X       x   x x   x  x     x  x ",
         " XXX                X        x   xxxx  x  xxxx   xxx ",
         " X     X   XXX       X       x     x   x      x    x ",
         " X     X          XXXX   x   x     x   x  xxxx     x ",]]


# Create Nx3 and Nx1 vectors to encode the messages above:
locations = []
features = []
for batchIdx, msg in enumerate(msgs):
    for y, line in enumerate(msg):
        for x, c in enumerate(line):
            if c == 'X':
                locations.append([y, x, batchIdx])
                features.append([1])
locations = torch.LongTensor(locations)
features = torch.FloatTensor(features).to(device)

input = input_layer([locations,features])
print('Input SparseConvNetTensor:', input)
output = model(input)

# Output is 2x32x10x10: our minibatch has 2 samples, the network has 32 output
# feature planes, and 10x10 is the spatial size of the output.
print('Output SparseConvNetTensor:', output)

traced_script_module = torch.jit.trace(model, input)
traced_script_module.save("test_model.pt")
```

This fails with error:
```bash
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    traced_script_module = torch.jit.trace(model, input)
  File "/home/marco.deltutto/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/marco.deltutto/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1033, in trace_module
    example_inputs = make_tuple(example_inputs)
  File "/home/marco.deltutto/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 706, in make_tuple
    return tuple(example_inputs)
TypeError: 'SparseConvNetTensor' object is not iterable
```

**Comment by bottler** [comment]
The library is not currently torchscript compatible, and I don't know how difficult it would be to make it so. For an operation to work with torchscript, I think it can't use pybind11 to interface with python, but should use other methods.

It would be interesting to know what you are trying to use torchscript and sparseconvnet together for.

**Comment by marcodeltutto** [comment]
Thanks @bottler! I have a model that uses sparseconvnet and I would like it to be executed by the TensorRT inference server, as shown [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_repository.html#pytorch-models). I guess there is no way to do this?

**Comment by bottler** [comment]
It is possible to add custom ops to torchscript, see [here](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html), and it looks like these can be used in tensorrt, see [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/custom_operation.html#pytorch).  I think it is technically possible for someone to adapt the interface of sparseconvnet so it works in that way, enabling your idea.

**Comment by btgraham** [comment]
Sorry, this is not supported yet.
