### ISSUE TITLE
Build in windows is failing

### ISSUE THREAD

**Issue by logicatcore** [facebookresearch/SparseConvNet#184]
Hello, I am trying to build the library in my Windows machine.

Initially I was missing C++ 14.0 but after having downloaded and installed, I have encountered this new issue and am not able to make much of it from the console output. 

I have installed pytorch with conda support in a conda virtual environment and have modified the command in "develop.sh" accordingly to trigger setup.py file execution by the python interpreter of the same environment.

I am not sure if I was supposed to choose some special path while installing "Microsoft Visual Studio Build Tools"

pytorch version : 1.5.1
python: 3.7

**Error Message**

``` 
(tf) D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master>C:\LegacyApp\Continuum\envs\tf\python.exe setup.py develop && python examples/hello-world.py
running develop
running egg_info
writing sparseconvnet.egg-info\PKG-INFO
writing dependency_links to sparseconvnet.egg-info\dependency_links.txt
writing top-level names to sparseconvnet.egg-info\top_level.txt
package init file 'sparseconvnet\SCN\__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info\SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info\SOURCES.txt'
running build_ext
C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'sparseconvnet.SCN' extension
Emitting ninja build file D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master/sparseconvnet/SCN/ -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include
-IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\incl
ude\THC -IC:\LegacyApp\Continuum\envs\tf\include -IC:\LegacyApp\Continuum\envs\tf\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\AT
LMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -c D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master\sparseconvnet\SCN\pybind.cpp /FoD:\DSUsers\uic77387\Repos\git_repos\Sparse
ConvNet-master\build\temp.win-amd64-3.7\Release\sparseconvnet/SCN/pybind.obj -std=c++14 -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/DSUsers/uic77387/Repos/git_repos/SparseConvNet-master/build/temp.win-amd64-3.7/Release/sparseconvnet/SCN/pybind.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master/sparseconvnet/SCN/ -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include -IC:\L
egacyApp\Continuum\envs\tf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH
C -IC:\LegacyApp\Continuum\envs\tf\include -IC:\LegacyApp\Continuum\envs\tf\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\I
NCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -c D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master\sparseconvnet\SCN\pybind.cpp /FoD:\DSUsers\uic77387\Repos\git_repos\SparseConvNe
t-master\build\temp.win-amd64-3.7\Release\sparseconvnet/SCN/pybind.obj -std=c++14 -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/2] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master/sparseconvnet/SCN/ -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include
-IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\incl
ude\THC -IC:\LegacyApp\Continuum\envs\tf\include -IC:\LegacyApp\Continuum\envs\tf\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\AT
LMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -c D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master\sparseconvnet\SCN\sparseconvnet_cpu.cpp /FoD:\DSUsers\uic77387\Repos\git_r
epos\SparseConvNet-master\build\temp.win-amd64-3.7\Release\sparseconvnet/SCN/sparseconvnet_cpu.obj -std=c++14 -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++
14
FAILED: D:/DSUsers/uic77387/Repos/git_repos/SparseConvNet-master/build/temp.win-amd64-3.7/Release/sparseconvnet/SCN/sparseconvnet_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -ID:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master/sparseconvnet/SCN/ -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include -IC:\L
egacyApp\Continuum\envs\tf\lib\site-packages\torch\include\torch\csrc\api\include -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH -IC:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\include\TH
C -IC:\LegacyApp\Continuum\envs\tf\include -IC:\LegacyApp\Continuum\envs\tf\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\I
NCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -c D:\DSUsers\uic77387\Repos\git_repos\SparseConvNet-master\sparseconvnet\SCN\sparseconvnet_cpu.cpp /FoD:\DSUsers\uic77387\Repos\git_repos\S
parseConvNet-master\build\temp.win-amd64-3.7\Release\sparseconvnet/SCN/sparseconvnet_cpu.obj -std=c++14 -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\LegacyApp\Continuum\envs\tf\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    zip_safe=False,
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\setuptools\command\develop.py", line 38, in run
    self.install_for_development()
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\LegacyApp\Continuum\envs\tf\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\LegacyApp\Continuum\envs\tf\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension 
```
Any inputs on how to solve this issue will be highly helpful, thanks.

**Comment by victoryc** [comment]
I am also getting quite similar errors. Any help would be greatly appreciated.

The main indicator seems to be the following error message:
Warning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))

**Comment by victoryc** [comment]
I managed to get this to build on Windows 10. I have left some notes about the main things I needed to do in the thread: https://github.com/facebookresearch/SparseConvNet/issues/128

**Comment by logicatcore** [comment]
Thanks a lot! Your instructions were very helpful. It took me some what more tinkering than your case but finally got it working.

**Comment by sds0810** [comment]
@logicatcore Hey, Could you pls tell me how to modify ?
thank you
