### ISSUE TITLE
Runtime Error When Running Examples

### ISSUE THREAD

**Issue by CaesarPan** [facebookresearch/SparseConvNet#28]
Hi Benjamin,

A runtime error raised when I ran `ResNet.py` or `VGGplus.py`:`RuntimeError: softmax(): argument 'input' (position 1) must be Variable, not torch.cuda.FloatTensor`

The full traceback was:

```
Traceback (most recent call last):
  File "VGGplus.py", line 42, in <module>
    'check_point': True,})
  File "/root/SparseConvNet/PyTorch/sparseconvnet/classificationTrainValidate.py", line 92, in ClassificationTrainValidate
    updateStats(stats, output.data, batch['target'].data, loss.data[0])
  File "/root/SparseConvNet/PyTorch/sparseconvnet/classificationTrainValidate.py", line 38, in updateStats
    stats['confusion matrix'].index_add_(0,target,F.softmax(output).data)
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 768, in softmax
    return torch._C._nn.softmax(input, dim)
RuntimeError: softmax(): argument 'input' (position 1) must be Variable, not torch.cuda.FloatTensor
```

The PyTorch version is 0.3. Thank you for your help.

**Comment by btgraham** [comment]
I have now tested with 0.3. Please git pull and try again!
Regards
Ben

**Comment by CaesarPan** [comment]
Sry but running 'VGGPlus.py' still yields error:

`KeyError: 'unexpected key "sparseModel.2.0.weight" in state_dict'`

Traceback:

```
Traceback (most recent call last):
  File "VGGplus.py", line 42, in <module>
    'check_point': True,})
  File "/root/SparseConvNet/PyTorch/sparseconvnet/classificationTrainValidate.py", line 71, in ClassificationTrainValidate
    model.load_state_dict(torch.load('model.pth'))
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "sparseModel.2.0.weight" in state_dict'
```

**Comment by btgraham** [comment]
Please delete model.pth, or alternatively set 'check_point' to False in VGGplus.py, line 42.
(It is trying to restart from a checkpoint, but for a different model).

**Comment by CaesarPan** [comment]
Yes it works, thank you very much!
