### ISSUE TITLE
Error while running unet.py in 3d_segmentation

### ISSUE THREAD

**Issue by DonDzundza** [facebookresearch/SparseConvNet#64]
I ran the FCN, it worked fine.
But when I ran unet.py, it rasied error:

Traceback (most recent call last):
  File "unet.py", line 148, in <module>
    predictions=model(batch['x'])
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "unet.py", line 34, in forward
    x=self.sparseModel(x)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/sparseconvnet-0.2-py3.6-linux-x86_64.egg/sparseconvnet/tables.py", line 39, in forward
    return [module(input) for module in self._modules.values()]
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/sparseconvnet-0.2-py3.6-linux-x86_64.egg/sparseconvnet/tables.py", line 39, in <listcomp>
    return [module(input) for module in self._modules.values()]
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhuang/anaconda3/envs/py36tf/lib/python3.6/site-packages/sparseconvnet-0.2-py3.6-linux-x86_64.egg/sparseconvnet/**convolution.py", line 37, in forward
    self.filter_size == input.spatial_size).all(), (input.spatial_size,output.spatial_size,self.filter_size,self.filter_stride)
AssertionError: (tensor([192, 192, 192]), tensor([95, 95, 95]), tensor([3, 3, 3]), tensor([2, 2, 2]))**

Seems like dimensions don't match up correctly. 

Please help. Thanks.

**Comment by btgraham** [comment]
Thanks for the report, fix pushed.
