### ISSUE TITLE
Error when running 3d_segmentation full convultion

### ISSUE THREAD

**Issue by nbardy** [facebookresearch/SparseConvNet#88]
Getting an error when trying to run the full convolutional example. The `unnet.py` runs well for me, but fully_convolutional fails. Having trouble figuring this error out.

```
Traceback (most recent call last):
  File "fully_convolutional.py", line 139, in <module>
    loss.backward()
  File "/opt/conda/lib/python2.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python2.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python2.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/Python-3.6.3/~/SparseConvNet/sparseconvnet/unPooling.py", line 57, in backward
    ctx.nFeaturesToDrop)
RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach() (set_sizes_contiguous at /opt/conda/conda-bld/pytorch-nightly_1553490705248/work/c10/core/TensorImpl.h:732)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fd4d0f52cf5 in /opt/conda/lib/python2.7/site-packages/torch/lib/libc10.so)
frame #1: THCTensor_resizeNd + 0xccb (0x7fd4d565c48b in /opt/conda/lib/python2.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: at::CUDAFloatType::_th_resize_as_(at::Tensor&, at::Tensor const&) const + 0x5c (0x7fd4d556134c in /opt/conda/lib/python2.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::native::resize_as_(at::Tensor&, at::Tensor const&) + 0x4a (0x7fd4d1901aea in /opt/conda/lib/python2.7/site-packages/torch/lib/libcaffe2.so)
frame #4: at::TypeDefault::resize_as_(at::Tensor&, at::Tensor const&) const + 0x5a (0x7fd4d1c2db6a in /opt/conda/lib/python2.7/site-packages/torch/lib/libcaffe2.so)
frame #5: torch::autograd::VariableType::resize_as_(at::Tensor&, at::Tensor const&) const + 0xcf (0x7fd4c9c752cf in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #6: void cuda_UnPooling_updateGradInput<float, 3>(at::Tensor, at::Tensor, at::Tensor, at::Tensor, Metadata<3>&, at::Tensor, at::Tensor, at::Tensor, long) + 0x117 (0x7fd4b1ba1fb7 in /Python-3.6.3/~/SparseConvNet/sparseconvnet/SCN.so)
frame #7: void UnPooling_updateGradInput<3>(at::Tensor, at::Tensor, at::Tensor, at::Tensor, Metadata<3>&, at::Tensor, at::Tensor, at::Tensor, long) + 0x123 (0x7fd4b1ba2493 in /Python-3.6.3/~/SparseConvNet/sparseconvnet/SCN.so)
frame #8: <unknown function> + 0x1a52f5 (0x7fd4b1c2b2f5 in /Python-3.6.3/~/SparseConvNet/sparseconvnet/SCN.so)
frame #9: <unknown function> + 0x197939 (0x7fd4b1c1d939 in /Python-3.6.3/~/SparseConvNet/sparseconvnet/SCN.so)
<omitting python frames>
frame #21: torch::autograd::PyFunction::apply(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> >&&) + 0x193 (0x7fd4fb0722b3 in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
frame #22: torch::autograd::Engine::evaluate_function(torch::autograd::FunctionTask&) + 0x3a6 (0x7fd4c9760246 in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #23: torch::autograd::Engine::thread_main(torch::autograd::GraphTask*) + 0xc0 (0x7fd4c9762270 in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #24: torch::autograd::Engine::thread_init(int) + 0x382 (0x7fd4c975f322 in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch.so.1)
frame #25: torch::autograd::python::PythonEngine::thread_init(int) + 0x2a (0x7fd4fb06cdda in /opt/conda/lib/python2.7/site-packages/torch/lib/libtorch_python.so)
frame #26: <unknown function> + 0xb8678 (0x7fd4ca6a2678 in /opt/conda/lib/python2.7/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #27: <unknown function> + 0x76db (0x7fd4ff6156db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #28: clone + 0x3f (0x7fd4feb9988f in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by btgraham** [comment]
Thanks for the bug report. Please try pulling and recompiling.

**Comment by nbardy** [comment]
@btgraham Fixed. Thanks!
